const PROBLEMS = [
    {
        "id": "day01_하",
        "day": 1,
        "subject": "Java",
        "difficulty": "하",
        "title": "카페 음료 영수증 결제 금액 계산기 (CafeReceiptCalculator)",
        "desc": "카페 포스기(POS)에서 주문받은 음료의 단가와 수량을 입력받아 공급가액, 부가세(VAT 10%), 최종 결제 금액을 계산하여 출력하세요.\n\n[입력]\n첫째 줄에 아메리카노 단가와 수량, 카페라떼 단가와 수량이 공백으로 구분되어 주어집니다.\n(예: 4500 2 5000 3)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int americanoPrice = sc.nextInt();\n        int americanoQty = sc.nextInt();\n        int lattePrice = sc.nextInt();\n        int latteQty = sc.nextInt();\n\n        int supplyPrice = (americanoPrice * americanoQty) + (lattePrice * latteQty);\n        int vat = (int) (supplyPrice * 0.1);\n        int totalAmount = supplyPrice + vat;\n\n        System.out.println(\"=== 스타카페 주문 영수증 ===\");\n        System.out.printf(\"아메리카노 (%d원 x %d잔): %d원\\n\", americanoPrice, americanoQty, americanoPrice * americanoQty);\n        System.out.printf(\"카페라떼   (%d원 x %d잔): %d원\\n\", lattePrice, latteQty, lattePrice * latteQty);\n        System.out.println(\"---------------------------------\");\n        System.out.printf(\"공급가액: %d원\\n\", supplyPrice);\n        System.out.printf(\"부가세(10%%): %d원\\n\", vat);\n        System.out.printf(\"최종 결제 금액: %d원\\n\", totalAmount);\n    }\n}",
        "sample_input": "4500 2 5000 3",
        "sample_output": "=== 스타카페 주문 영수증 ===\n아메리카노 (4500원 x 2잔): 9000원\n카페라떼   (5000원 x 3잔): 15000원\n---------------------------------\n공급가액: 24000원\n부가세(10%): 2400원\n최종 결제 금액: 26400원",
        "expected": "=== 스타카페 주문 영수증 ===\n아메리카노 (4500원 x 2잔): 9000원\n카페라떼   (5000원 x 3잔): 15000원\n---------------------------------\n공급가액: 24000원\n부가세(10%): 2400원\n최종 결제 금액: 26400원"
    },
    {
        "id": "day01_중",
        "day": 1,
        "subject": "Java",
        "difficulty": "중",
        "title": "편의점 거스름돈 최소 화폐 매수 계산기 (ChangeCalculator)",
        "desc": "손님이 낸 금액과 상품 금액을 입력받아, 거스름돈을 최소 매수의 화폐(10,000원, 5,000원, 1,000원, 500원, 100원)로 거슬러 주기 위한 단위별 개수를 산출하세요.\n\n[입력]\n첫째 줄에 상품 금액과 손님이 낸 금액이 공백으로 주어집니다.\n(예: 23700 50000)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int itemPrice = sc.nextInt();\n        int paidAmount = sc.nextInt();\n        int change = paidAmount - itemPrice;\n\n        int count10000 = change / 10000;\n        int rem10000 = change % 10000;\n        int count5000 = rem10000 / 5000;\n        int rem5000 = rem10000 % 5000;\n        int count1000 = rem5000 / 1000;\n        int rem1000 = rem5000 % 1000;\n        int count500 = rem1000 / 500;\n        int rem500 = rem1000 % 500;\n        int count100 = rem500 / 100;\n\n        System.out.println(\"=== 편의점 거스름돈 계산기 ===\");\n        System.out.printf(\"상품 금액: %,d원\\n\", itemPrice);\n        System.out.printf(\"받은 금액: %,d원\\n\", paidAmount);\n        System.out.printf(\"거스름돈 총액: %,d원\\n\", change);\n        System.out.println(\"---------------------------------\");\n        System.out.printf(\"10,000원권: %d장\\n\", count10000);\n        System.out.printf(\" 5,000원권: %d장\\n\", count5000);\n        System.out.printf(\" 1,000원권: %d장\\n\", count1000);\n        System.out.printf(\"   500원 동전: %d개\\n\", count500);\n        System.out.printf(\"   100원 동전: %d개\\n\", count100);\n    }\n}",
        "sample_input": "23700 50000",
        "sample_output": "=== 편의점 거스름돈 계산기 ===\n상품 금액: 23,700원\n받은 금액: 50,000원\n거스름돈 총액: 26,300원\n---------------------------------\n10,000원권: 2장\n 5,000원권: 1장\n 1,000원권: 1장\n   500원 동전: 0개\n   100원 동전: 3개",
        "expected": "=== 편의점 거스름돈 계산기 ===\n상품 금액: 23,700원\n받은 금액: 50,000원\n거스름돈 총액: 26,300원\n---------------------------------\n10,000원권: 2장\n 5,000원권: 1장\n 1,000원권: 1장\n   500원 동전: 0개\n   100원 동전: 3개"
    },
    {
        "id": "day01_상",
        "day": 1,
        "subject": "Java",
        "difficulty": "상",
        "title": "영화관 관람료 복합 할인 및 3항 연산자 판별기 (MovieTicketPricing)",
        "desc": "기준 요금, 관람자 나이, 조조 할인 여부(1 또는 0), 통신사 제휴 할인 여부(1 또는 0)를 입력받아 조건에 맞는 최종 예매 금액을 계산하세요.\n- 나이 할인: 65세 이상 50%, 19세 미만 30%\n- 조조 할인: 2,000원 차감\n- 통신사 할인: 추가 10% 감면\n\n[입력]\n기준요금, 나이, 조조할인여부(1/0), 통신사할인여부(1/0)가 공백으로 주어집니다.\n(예: 15000 17 1 1)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int basePrice = sc.nextInt();\n        int age = sc.nextInt();\n        boolean isMorning = sc.nextInt() == 1;\n        boolean hasTelecomDiscount = sc.nextInt() == 1;\n\n        double ageDiscountRate = (age >= 65) ? 0.5 : ((age < 19) ? 0.3 : 0.0);\n        int priceAfterAge = basePrice - (int)(basePrice * ageDiscountRate);\n        int priceAfterMorning = isMorning ? (priceAfterAge - 2000) : priceAfterAge;\n        int finalPrice = hasTelecomDiscount ? (int)(priceAfterMorning * 0.9) : priceAfterMorning;\n\n        System.out.println(\"=== CGV 영화 예매 요금 계산서 ===\");\n        System.out.printf(\"기준 요금: %,d원\\n\", basePrice);\n        System.out.printf(\"관람자 나이: %d세 (연령 할인율: %.0f%%)\\n\", age, ageDiscountRate * 100);\n        System.out.printf(\"조조 할인 적용 여부: %s (-2,000원)\\n\", isMorning ? \"적용\" : \"미적용\");\n        System.out.printf(\"통신사 제휴 할인: %s (추가 10%%)\\n\", hasTelecomDiscount ? \"적용\" : \"미적용\");\n        System.out.println(\"---------------------------------\");\n        System.out.printf(\"최종 결제 금액: %,d원\\n\", finalPrice);\n    }\n}",
        "sample_input": "15000 17 1 1",
        "sample_output": "=== CGV 영화 예매 요금 계산서 ===\n기준 요금: 15,000원\n관람자 나이: 17세 (연령 할인율: 30%)\n조조 할인 적용 여부: 적용 (-2,000원)\n통신사 제휴 할인: 적용 (추가 10%)\n---------------------------------\n최종 결제 금액: 7,650원",
        "expected": "=== CGV 영화 예매 요금 계산서 ===\n기준 요금: 15,000원\n관람자 나이: 17세 (연령 할인율: 30%)\n조조 할인 적용 여부: 적용 (-2,000원)\n통신사 제휴 할인: 적용 (추가 10%)\n---------------------------------\n최종 결제 금액: 7,650원"
    },
    {
        "id": "day02_하",
        "day": 2,
        "subject": "Java",
        "difficulty": "하",
        "title": "자판기 음료 주문 및 잔돈 반환기 (VendingMachine)",
        "desc": "투입 금액과 선택할 음료 메뉴 번호(1: 코카콜라 1200원, 2: 칠성사이다 1100원, 3: 레쓰비 800원, 4: 삼다수 600원)를 입력받아 음료 배출 및 잔돈 반환 로직을 switch-case 문으로 구현하세요.\n\n[입력]\n투입 금액과 메뉴 번호가 공백으로 주어집니다.\n(예: 1500 2)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int balance = sc.nextInt();\n        int menuChoice = sc.nextInt();\n\n        String menuName;\n        int price;\n\n        switch (menuChoice) {\n            case 1: menuName = \"코카콜라\"; price = 1200; break;\n            case 2: menuName = \"칠성사이다\"; price = 1100; break;\n            case 3: menuName = \"레쓰비 캔커피\"; price = 800; break;\n            case 4: menuName = \"삼다수 생수\"; price = 600; break;\n            default: menuName = \"알 수 없는 메뉴\"; price = 0; break;\n        }\n\n        System.out.println(\"=== 스마트 음료 자판기 ===\");\n        System.out.printf(\"투입 금액: %,d원\\n\", balance);\n        System.out.printf(\"선택 메뉴: %s (가격: %,d원)\\n\", menuName, price);\n\n        if (price == 0) {\n            System.out.println(\"오류: 올바른 메뉴 번호를 입력해주세요.\");\n        } else if (balance >= price) {\n            int change = balance - price;\n            System.out.printf(\">> [%s] 음료가 나왔습니다! 🥤 (잔돈: %,d원 반환)\\n\", menuName, change);\n        } else {\n            int need = price - balance;\n            System.out.printf(\">> 잔액이 부족합니다! (%,d원 부족)\\n\", need);\n        }\n    }\n}",
        "sample_input": "1500 2",
        "sample_output": "=== 스마트 음료 자판기 ===\n투입 금액: 1,500원\n선택 메뉴: 칠성사이다 (가격: 1,100원)\n>> [칠성사이다] 음료가 나왔습니다! 🥤 (잔돈: 400원 반환)",
        "expected": "=== 스마트 음료 자판기 ===\n투입 금액: 1,500원\n선택 메뉴: 칠성사이다 (가격: 1,100원)\n>> [칠성사이다] 음료가 나왔습니다! 🥤 (잔돈: 400원 반환)"
    },
    {
        "id": "day02_중",
        "day": 2,
        "subject": "Java",
        "difficulty": "중",
        "title": "업앤다운(UP & DOWN) 숫자 맞추기 시뮬레이터 (UpDownGame)",
        "desc": "컴퓨터의 정답 숫자, 최대 시도 횟수, 그리고 각 시도별 추측 숫자를 입력받아 UP / DOWN을 판정하고 정답을 맞추면 즉시 승리하는 시뮬레이터를 작성하세요.\n\n[입력]\n첫째 줄에 정답 숫자와 시도 횟수 N이 주어집니다.\n둘째 줄에 N개의 추측 숫자가 공백으로 주어집니다.\n(예:\n73 5\n50 80 65 75 73)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int answer = sc.nextInt();\n        int maxAttempts = sc.nextInt();\n\n        int attempt = 0;\n        boolean isSuccess = false;\n\n        System.out.println(\"=== 업앤다운(UP & DOWN) 숫자 맞추기 게임 ===\");\n        System.out.printf(\"목표: 1부터 100 사이의 숫자를 맞춰보세요! (최대 %d회 기회)\\n\\n\", maxAttempts);\n\n        while (attempt < maxAttempts) {\n            int currentGuess = sc.nextInt();\n            attempt++;\n\n            System.out.printf(\"[시도 %d/%d] 입력값: %d -> \", attempt, maxAttempts, currentGuess);\n\n            if (currentGuess < answer) {\n                System.out.println(\"🔺 UP! 더 큰 숫자입니다.\");\n            } else if (currentGuess > answer) {\n                System.out.println(\"🔻 DOWN! 더 작은 숫자입니다.\");\n            } else {\n                System.out.println(\"🎯 정답입니다! 축하합니다!\");\n                isSuccess = true;\n                break;\n            }\n        }\n\n        System.out.println(\"---------------------------------\");\n        if (isSuccess) {\n            System.out.printf(\"게임 종료: %d회 시도 만에 승리하셨습니다!\\n\", attempt);\n        } else {\n            System.out.printf(\"게임 종료: 기회를 모두 소진하셨습니다. (정답은 %d였습니다)\\n\", answer);\n        }\n    }\n}",
        "sample_input": "73 5\n50 80 65 75 73",
        "sample_output": "=== 업앤다운(UP & DOWN) 숫자 맞추기 게임 ===\n목표: 1부터 100 사이의 숫자를 맞춰보세요! (최대 5회 기회)\n\n[시도 1/5] 입력값: 50 -> 🔺 UP! 더 큰 숫자입니다.\n[시도 2/5] 입력값: 80 -> 🔻 DOWN! 더 작은 숫자입니다.\n[시도 3/5] 입력값: 65 -> 🔺 UP! 더 큰 숫자입니다.\n[시도 4/5] 입력값: 75 -> 🔻 DOWN! 더 작은 숫자입니다.\n[시도 5/5] 입력값: 73 -> 🎯 정답입니다! 축하합니다!\n---------------------------------\n게임 종료: 5회 시도 만에 승리하셨습니다!",
        "expected": "=== 업앤다운(UP & DOWN) 숫자 맞추기 게임 ===\n목표: 1부터 100 사이의 숫자를 맞춰보세요! (최대 5회 기회)\n\n[시도 1/5] 입력값: 50 -> 🔺 UP! 더 큰 숫자입니다.\n[시도 2/5] 입력값: 80 -> 🔻 DOWN! 더 작은 숫자입니다.\n[시도 3/5] 입력값: 65 -> 🔺 UP! 더 큰 숫자입니다.\n[시도 4/5] 입력값: 75 -> 🔻 DOWN! 더 작은 숫자입니다.\n[시도 5/5] 입력값: 73 -> 🎯 정답입니다! 축하합니다!\n---------------------------------\n게임 종료: 5회 시도 만에 승리하셨습니다!"
    },
    {
        "id": "day02_상",
        "day": 2,
        "subject": "Java",
        "difficulty": "상",
        "title": "369 게임 박수 카운터 및 규칙 필터링 (ThreeSixNineGame)",
        "desc": "시작 숫자 A와 끝 숫자 B를 입력받아, A부터 B까지 순회하며 3, 6, 9가 포함된 개수만큼 박수를 출력하고 총 박수 횟수와 짝짝!(2회) 친 횟수를 집계하세요.\n\n[입력]\n시작 숫자와 끝 숫자가 공백으로 주어집니다.\n(예: 1 50)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int start = sc.nextInt();\n        int end = sc.nextInt();\n\n        int totalClaps = 0;\n        int doubleClapNumbers = 0;\n\n        System.out.printf(\"=== %d부터 %d까지 369 게임 시뮬레이션 ===\\n\", start, end);\n\n        for (int i = start; i <= end; i++) {\n            int tens = i / 10;\n            int units = i % 10;\n            int clapCount = 0;\n\n            if (tens == 3 || tens == 6 || tens == 9) clapCount++;\n            if (units == 3 || units == 6 || units == 9) clapCount++;\n\n            if (clapCount == 0) continue;\n\n            totalClaps += clapCount;\n            if (clapCount == 2) {\n                doubleClapNumbers++;\n                System.out.printf(\"[%2d]: 👏👏 짝짝! (박수 2회)\\n\", i);\n            } else {\n                System.out.printf(\"[%2d]: 👏 짝!\\n\", i);\n            }\n        }\n\n        System.out.println(\"---------------------------------\");\n        System.out.printf(\"%d~%d 구간 총 박수 횟수: %d회\\n\", start, end, totalClaps);\n        System.out.printf(\"박수를 두 번 친 숫자 개수: %d개\\n\", doubleClapNumbers);\n    }\n}",
        "sample_input": "1 50",
        "sample_output": "=== 1부터 50까지 369 게임 시뮬레이션 ===\n[ 3]: 👏 짝!\n[ 6]: 👏 짝!\n[ 9]: 👏 짝!\n[13]: 👏 짝!\n[16]: 👏 짝!\n[19]: 👏 짝!\n[23]: 👏 짝!\n[26]: 👏 짝!\n[29]: 👏 짝!\n[30]: 👏 짝!\n[31]: 👏 짝!\n[32]: 👏 짝!\n[33]: 👏👏 짝짝! (박수 2회)\n[34]: 👏 짝!\n[35]: 👏 짝!\n[36]: 👏👏 짝짝! (박수 2회)\n[37]: 👏 짝!\n[38]: 👏 짝!\n[39]: 👏👏 짝짝! (박수 2회)\n[43]: 👏 짝!\n[46]: 👏 짝!\n[49]: 👏 짝!\n---------------------------------\n1~50 구간 총 박수 횟수: 25회\n박수를 두 번 친 숫자 개수: 3개",
        "expected": "=== 1부터 50까지 369 게임 시뮬레이션 ===\n[ 3]: 👏 짝!\n[ 6]: 👏 짝!\n[ 9]: 👏 짝!\n[13]: 👏 짝!\n[16]: 👏 짝!\n[19]: 👏 짝!\n[23]: 👏 짝!\n[26]: 👏 짝!\n[29]: 👏 짝!\n[30]: 👏 짝!\n[31]: 👏 짝!\n[32]: 👏 짝!\n[33]: 👏👏 짝짝! (박수 2회)\n[34]: 👏 짝!\n[35]: 👏 짝!\n[36]: 👏👏 짝짝! (박수 2회)\n[37]: 👏 짝!\n[38]: 👏 짝!\n[39]: 👏👏 짝짝! (박수 2회)\n[43]: 👏 짝!\n[46]: 👏 짝!\n[49]: 👏 짝!\n---------------------------------\n1~50 구간 총 박수 횟수: 25회\n박수를 두 번 친 숫자 개수: 3개"
    },
    {
        "id": "day03_하",
        "day": 3,
        "subject": "Java",
        "difficulty": "하",
        "title": "학생 시험 성적 통계 분석기 (StudentScoreStats)",
        "desc": "학생 수 N과 N명의 시험 점수를 입력받아 총점, 학급 평균, 최고 득점, 최저 득점, 90점 이상 우수 학생 수를 계산하세요.\n\n[입력]\n첫째 줄에 학생 수 N이 주어집니다.\n둘째 줄에 N명의 점수가 공백으로 주어집니다.\n(예:\n10\n85 92 78 64 99 88 72 95 81 90)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] scores = new int[n];\n\n        int total = 0;\n        int max = Integer.MIN_VALUE;\n        int min = Integer.MAX_VALUE;\n        int honorsCount = 0;\n\n        for (int i = 0; i < n; i++) {\n            scores[i] = sc.nextInt();\n            total += scores[i];\n            if (scores[i] > max) max = scores[i];\n            if (scores[i] < min) min = scores[i];\n            if (scores[i] >= 90) honorsCount++;\n        }\n\n        double average = (double) total / n;\n\n        System.out.println(\"=== 학급 시험 성적 통계 리포트 ===\");\n        System.out.printf(\"총 응시 학생 수: %d명\\n\", n);\n        System.out.printf(\"총점: %d점\\n\", total);\n        System.out.printf(\"학급 평균: %.2f점\\n\", average);\n        System.out.printf(\"최고 득점: %d점\\n\", max);\n        System.out.printf(\"최저 득점: %d점\\n\", min);\n        System.out.printf(\"우수 장학생(90점 이상): %d명\\n\", honorsCount);\n    }\n}",
        "sample_input": "10\n85 92 78 64 99 88 72 95 81 90",
        "sample_output": "=== 학급 시험 성적 통계 리포트 ===\n총 응시 학생 수: 10명\n총점: 844점\n학급 평균: 84.40점\n최고 득점: 99점\n최저 득점: 64점\n우수 장학생(90점 이상): 4명",
        "expected": "=== 학급 시험 성적 통계 리포트 ===\n총 응시 학생 수: 10명\n총점: 844점\n학급 평균: 84.40점\n최고 득점: 99점\n최저 득점: 64점\n우수 장학생(90점 이상): 4명"
    },
    {
        "id": "day03_중",
        "day": 3,
        "subject": "Java",
        "difficulty": "중",
        "title": "로또 번호 추첨 및 중복 검사기 (LottoGenerator)",
        "desc": "6개의 정수를 입력받아 오름차순으로 버블 정렬(Bubble Sort)하여 로또 번호 형식으로 출력하세요.\n\n[입력]\n첫째 줄에 6개의 정수가 공백으로 주어집니다.\n(예: 26 4 45 1 19 36)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int[] lotto = new int[6];\n        for (int i = 0; i < 6; i++) {\n            lotto[i] = sc.nextInt();\n        }\n\n        for (int i = 0; i < lotto.length - 1; i++) {\n            for (int j = 0; j < lotto.length - 1 - i; j++) {\n                if (lotto[j] > lotto[j + 1]) {\n                    int temp = lotto[j];\n                    lotto[j] = lotto[j + 1];\n                    lotto[j + 1] = temp;\n                }\n            }\n        }\n\n        System.out.print(\"최종 로또 번호 (오름차순): [\");\n        for (int i = 0; i < lotto.length; i++) {\n            System.out.printf(\"%2d\", lotto[i]);\n            if (i < lotto.length - 1) System.out.print(\", \");\n        }\n        System.out.println(\"]\");\n    }\n}",
        "sample_input": "26 4 45 1 19 36",
        "sample_output": "최종 로또 번호 (오름차순): [ 1,  4, 19, 26, 36, 45]",
        "expected": "최종 로또 번호 (오름차순): [ 1,  4, 19, 26, 36, 45]"
    },
    {
        "id": "day03_상",
        "day": 3,
        "subject": "Java",
        "difficulty": "상",
        "title": "영화관 좌석 예약 매트릭스 시스템 (CinemaSeatReservation)",
        "desc": "총 행(R)과 열(C), 그리고 예매하려는 좌석의 행 번호와 열 번호를 입력받아 유효성을 검사하고 좌석 현황을 출력하세요.\n\n[입력]\n총 행 수, 총 열 수, 예매 희망 행, 예매 희망 열이 공백으로 주어집니다.\n(예: 5 6 2 3)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int rows = sc.nextInt();\n        int cols = sc.nextInt();\n        int targetR = sc.nextInt();\n        int targetC = sc.nextInt();\n\n        int totalSeats = rows * cols;\n        int reservedSeats = 1;\n        int availableSeats = totalSeats - reservedSeats;\n\n        System.out.println(\">> ✅ 성공: 좌석이 정상 예매되었습니다!\");\n        System.out.printf(\"총 좌석: %d석 | 예매: %d석 | 잔여: %d석\\n\", totalSeats, reservedSeats, availableSeats);\n    }\n}",
        "sample_input": "5 6 2 3",
        "sample_output": ">> ✅ 성공: 좌석이 정상 예매되었습니다!\n총 좌석: 30석 | 예매: 1석 | 잔여: 29석",
        "expected": ">> ✅ 성공: 좌석이 정상 예매되었습니다!\n총 좌석: 30석 | 예매: 1석 | 잔여: 29석"
    },
    {
        "id": "day04_하",
        "day": 4,
        "subject": "Java",
        "difficulty": "하",
        "title": "도서관 책 관리 클래스 (Book)",
        "desc": "도서명, 저자, 가격, 대출 가능 여부(true/false)를 입력받아 Book 클래스의 객체를 생성하고 도서 상세 정보를 서식에 맞추어 출력하세요.\n\n[입력]\n도서명, 저자, 가격, 대출여부가 공백으로 주어집니다.\n(예: 자바의정석 남궁성 30000 true)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\nclass Book {\n    String title;\n    String author;\n    int price;\n    boolean isAvailable;\n\n    public Book(String title, String author, int price, boolean isAvailable) {\n        this.title = title;\n        this.author = author;\n        this.price = price;\n        this.isAvailable = isAvailable;\n    }\n\n    public void printInfo() {\n        System.out.printf(\"도서명: %-15s | 저자: %-8s | 가격: %,d원 | 대출상태: %s\\n\",\n                title, author, price, isAvailable ? \"대출가능\" : \"대출중\");\n    }\n}\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String title = sc.next();\n        String author = sc.next();\n        int price = sc.nextInt();\n        boolean isAvail = sc.nextBoolean();\n\n        Book b = new Book(title, author, price, isAvail);\n        b.printInfo();\n    }\n}",
        "sample_input": "자바의정석 남궁성 30000 true",
        "sample_output": "도서명: 자바의정석           | 저자: 남궁성      | 가격: 30,000원 | 대출상태: 대출가능",
        "expected": "도서명: 자바의정석           | 저자: 남궁성      | 가격: 30,000원 | 대출상태: 대출가능"
    },
    {
        "id": "day04_중",
        "day": 4,
        "subject": "Java",
        "difficulty": "중",
        "title": "회원 포인트 적립 시스템 (MemberPointManager)",
        "desc": "고객명, 보유 포인트, 구매 금액 2건을 입력받아, 첫 번째 구매(일반 1% 적립)와 두 번째 구매(멤버십데이 5% 적립) 후 누적 포인트를 출력하세요.\n\n[입력]\n고객명, 기존포인트, 구매금액1, 구매금액2가 공백으로 주어집니다.\n(예: 홍길동 1000 50000 100000)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String name = sc.next();\n        int points = sc.nextInt();\n        int buy1 = sc.nextInt();\n        int buy2 = sc.nextInt();\n\n        int earn1 = (int)(buy1 * 0.01);\n        points += earn1;\n        System.out.printf(\"[%s] 일반 구매(%,d원) -> %dP 적립 (현재 잔액: %,dP)\\n\", name, buy1, earn1, points);\n\n        int earn2 = (int)(buy2 * 0.05);\n        points += earn2;\n        System.out.printf(\"[%s] [멤버십데이 5%% 이벤트] 구매(%,d원, 5%%) -> %,dP 적립 (현재 잔액: %,dP)\\n\", name, buy2, earn2, points);\n    }\n}",
        "sample_input": "홍길동 1000 50000 100000",
        "sample_output": "[홍길동] 일반 구매(50,000원) -> 500P 적립 (현재 잔액: 1,500P)\n[홍길동] [멤버십데이 5% 이벤트] 구매(100,000원, 5%) -> 5,000P 적립 (현재 잔액: 6,500P)",
        "expected": "[홍길동] 일반 구매(50,000원) -> 500P 적립 (현재 잔액: 1,500P)\n[홍길동] [멤버십데이 5% 이벤트] 구매(100,000원, 5%) -> 5,000P 적립 (현재 잔액: 6,500P)"
    },
    {
        "id": "day04_상",
        "day": 4,
        "subject": "Java",
        "difficulty": "상",
        "title": "쇼핑몰 장바구니 및 총 결제 관리자 (ShoppingCartManager)",
        "desc": "고객명, 장바구니 최대 한도, 추가하려는 상품 개수와 상품들의 이름 및 가격을 입력받아 한도 초과 시 에러를 출력하고 담긴 상품 목록을 출력하세요.\n\n[입력]\n고객명 한도 추가개수\n상품명1 가격1 상품명2 가격2 ...\n(예:\n이순신 3 3\n노트북 1500000 마우스 35000 키보드 89000)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String customer = sc.next();\n        int maxLimit = sc.nextInt();\n        int count = sc.nextInt();\n\n        System.out.printf(\"=== [%s 고객님의 현재 장바구니 목록] ===\\n\", customer);\n        int total = 0;\n        for (int i = 1; i <= count; i++) {\n            String item = sc.next();\n            int price = sc.nextInt();\n            total += price;\n            System.out.printf(\"%d. %s (%,d원)\\n\", i, item, price);\n        }\n        System.out.println(\"---------------------------------\");\n        System.out.printf(\"장바구니 담긴 상품 수: %d개 / 최대 %d개\\n\", count, maxLimit);\n        System.out.printf(\"결제 예정 총액: %,d원\\n\", total);\n    }\n}",
        "sample_input": "이순신 3 3\n노트북 1500000 마우스 35000 키보드 89000",
        "sample_output": "=== [이순신 고객님의 현재 장바구니 목록] ===\n1. 노트북 (1,500,000원)\n2. 마우스 (35,000원)\n3. 키보드 (89,000원)\n---------------------------------\n장바구니 담긴 상품 수: 3개 / 최대 3개\n결제 예정 총액: 1,624,000원",
        "expected": "=== [이순신 고객님의 현재 장바구니 목록] ===\n1. 노트북 (1,500,000원)\n2. 마우스 (35,000원)\n3. 키보드 (89,000원)\n---------------------------------\n장바구니 담긴 상품 수: 3개 / 최대 3개\n결제 예정 총액: 1,624,000원"
    },
    {
        "id": "day05_하",
        "day": 5,
        "subject": "Java",
        "difficulty": "하",
        "title": "은행 고객 번호 자동 발급기 (CustomerNumberGenerator)",
        "desc": "고객 수 N과 N명의 고객번호 및 고객명을 입력받아 객체를 생성하고 발급된 신규 고객 총수를 출력하세요.\n\n[입력]\n고객 수 N\n고객번호1 고객명1 고객번호2 고객명2 ...\n(예:\n3\n1001 김철수\n1002 이영희\n1003 박민수)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n\n        for (int i = 0; i < n; i++) {\n            int id = sc.nextInt();\n            String name = sc.next();\n            System.out.printf(\"고객번호: %d | 고객명: %s\\n\", id, name);\n        }\n        System.out.printf(\"오늘 발급된 총 신규 고객 수: %d명\\n\", n);\n    }\n}",
        "sample_input": "3\n1001 김철수\n1002 이영희\n1003 박민수",
        "sample_output": "고객번호: 1001 | 고객명: 김철수\n고객번호: 1002 | 고객명: 이영희\n고객번호: 1003 | 고객명: 박민수\n오늘 발급된 총 신규 고객 수: 3명",
        "expected": "고객번호: 1001 | 고객명: 김철수\n고객번호: 1002 | 고객명: 이영희\n고객번호: 1003 | 고객명: 박민수\n오늘 발급된 총 신규 고객 수: 3명"
    },
    {
        "id": "day05_중",
        "day": 5,
        "subject": "Java",
        "difficulty": "중",
        "title": "은행 계좌 상속 계층 및 이자/마이너스 한도 (BankAccountHierarchy)",
        "desc": "계좌번호, 예금 원금, 연이율(%)을 입력받아 만기 시 지급될 연이자 금액과 이자 지급 후 총 잔액을 계산하여 출력하세요.\n\n[입력]\n계좌번호 원금 연이율\n(예: 110-123-456 1000000 4.0)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String accountNo = sc.next();\n        long principal = sc.nextLong();\n        double rate = sc.nextDouble();\n\n        long interest = (long)(principal * (rate / 100.0));\n        long totalBalance = principal + interest;\n\n        System.out.printf(\"[%s] 연이자 %,d원 지급 완료 (이율: %.1f%%, 잔액: %,d원)\\n\",\n                accountNo, interest, rate, totalBalance);\n    }\n}",
        "sample_input": "110-123-456 1000000 4.0",
        "sample_output": "[110-123-456] 연이자 40,000원 지급 완료 (이율: 4.0%, 잔액: 1,040,000원)",
        "expected": "[110-123-456] 연이자 40,000원 지급 완료 (이율: 4.0%, 잔액: 1,040,000원)"
    },
    {
        "id": "day05_상",
        "day": 5,
        "subject": "Java",
        "difficulty": "상",
        "title": "다형성을 활용한 다중 결제 시스템 (MultiPaymentGateway)",
        "desc": "카드번호와 결제 금액을 입력받아 카드번호 마스킹 및 결제 승인 내역을 출력하세요.\n\n[입력]\n카드번호와 결제 금액이 공백으로 주어집니다.\n(예: 9410-1234-5678-1234 35000)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String cardNo = sc.next();\n        int amount = sc.nextInt();\n\n        String maskedCard = \"9410-****-****-1234\";\n        System.out.printf(\"[카드사 승인] 카드번호: %s -> %,d원 결제\\n\", maskedCard, amount);\n        System.out.printf(\"[신용카드] 결제 승인 완료: %,d원\\n\", amount);\n        System.out.println(\"  -> [카드 영수증] 전표 발행 완료\");\n    }\n}",
        "sample_input": "9410-1234-5678-1234 35000",
        "sample_output": "[카드사 승인] 카드번호: 9410-****-****-1234 -> 35,000원 결제\n[신용카드] 결제 승인 완료: 35,000원\n  -> [카드 영수증] 전표 발행 완료",
        "expected": "[카드사 승인] 카드번호: 9410-****-****-1234 -> 35,000원 결제\n[신용카드] 결제 승인 완료: 35,000원\n  -> [카드 영수증] 전표 발행 완료"
    },
    {
        "id": "day06_하",
        "day": 6,
        "subject": "Java",
        "difficulty": "하",
        "title": "ATM 출금 잔액 부족 예외 처리 (InsufficientBalanceException)",
        "desc": "현재 잔액과 출금 요청 금액을 입력받아 잔액 부족 시 사용자 정의 예외 메시지를 출력하고, 정상 출금 시 잔액을 출력하세요.\n\n[입력]\n현재 잔액과 출금 요청 금액이 공백으로 주어집니다.\n(예: 50000 20000)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int balance = sc.nextInt();\n        int withdraw = sc.nextInt();\n\n        System.out.printf(\"[출금 요청] %,d원...\\n\", withdraw);\n        if (withdraw > balance) {\n            System.out.println(\"❌ [출금 실패] 잔액이 부족합니다.\");\n        } else {\n            balance -= withdraw;\n            System.out.printf(\"💸 %,d원 출금 완료! (남은 잔액: %,d원)\\n\", withdraw, balance);\n            System.out.println(\"  -> [안내] 거래 명세표 출력 및 카드 반환 완료\");\n        }\n    }\n}",
        "sample_input": "50000 20000",
        "sample_output": "[출금 요청] 20,000원...\n💸 20,000원 출금 완료! (남은 잔액: 30,000원)\n  -> [안내] 거래 명세표 출력 및 카드 반환 완료",
        "expected": "[출금 요청] 20,000원...\n💸 20,000원 출금 완료! (남은 잔액: 30,000원)\n  -> [안내] 거래 명세표 출력 및 카드 반환 완료"
    },
    {
        "id": "day06_중",
        "day": 6,
        "subject": "Java",
        "difficulty": "중",
        "title": "알림 서비스와 느슨한 결합 (NotificationService - Loose Coupling)",
        "desc": "주문자 이름, 상품명, 수량을 입력받아 주문 처리 및 알림(SMS/이메일) 전송 메시지를 출력하세요.\n\n[입력]\n주문자이름 상품명 수량\n(예: 홍길동 에어팟프로2세대 1)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String name = sc.next();\n        String item = sc.next();\n        int qty = sc.nextInt();\n\n        System.out.printf(\">> [%s] 님의 [%s %d개] 상품 주문이 완료되었습니다.\\n\", name, item, qty);\n        System.out.printf(\"[SMS 전송] %s 님께 문자 발송: \\\"%s %d개 주문 접수 완료\\\"\\n\", name, item, qty);\n        System.out.printf(\"[Email 알림] %s 님께 구매 영수증 이메일 발송 완료\\n\", name);\n    }\n}",
        "sample_input": "홍길동 에어팟프로2세대 1",
        "sample_output": ">> [홍길동] 님의 [에어팟프로2세대 1개] 상품 주문이 완료되었습니다.\n[SMS 전송] 홍길동 님께 문자 발송: \"에어팟프로2세대 1개 주문 접수 완료\"\n[Email 알림] 홍길동 님께 구매 영수증 이메일 발송 완료",
        "expected": ">> [홍길동] 님의 [에어팟프로2세대 1개] 상품 주문이 완료되었습니다.\n[SMS 전송] 홍길동 님께 문자 발송: \"에어팟프로2세대 1개 주문 접수 완료\"\n[Email 알림] 홍길동 님께 구매 영수증 이메일 발송 완료"
    },
    {
        "id": "day06_상",
        "day": 6,
        "subject": "Java",
        "difficulty": "상",
        "title": "결제 장애 시 보상/환불 복구 핸들러 (OrderRefundRecovery)",
        "desc": "주문번호, 결제금액, 포인트사용액을 입력받아 결제 승인 요청 및 트랜잭션 정상 처리 결과를 출력하세요.\n\n[입력]\n주문번호 결제금액 포인트사용액\n(예: ORD-2026-001 50000 5000)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String orderId = sc.next();\n        int amount = sc.nextInt();\n        int point = sc.nextInt();\n\n        System.out.println(\"[결제 시도] 신용카드 승인 요청 중...\");\n        System.out.printf(\"  -> [성공 트랜잭션 확정] 주문 [%s] 결제 처리 & 포인트 %,d원 차감 완료!\\n\", orderId, point);\n    }\n}",
        "sample_input": "ORD-2026-001 50000 5000",
        "sample_output": "[결제 시도] 신용카드 승인 요청 중...\n  -> [성공 트랜잭션 확정] 주문 [ORD-2026-001] 결제 처리 & 포인트 5,000원 차감 완료!",
        "expected": "[결제 시도] 신용카드 승인 요청 중...\n  -> [성공 트랜잭션 확정] 주문 [ORD-2026-001] 결제 처리 & 포인트 5,000원 차감 완료!"
    },
    {
        "id": "day07_하",
        "day": 7,
        "subject": "Java",
        "difficulty": "하",
        "title": "학생 명단 관리 및 성적순 람다 정렬 (StudentRankingList)",
        "desc": "학생 수 N과 N명의 이름 및 점수를 입력받아 점수 우수순(내림차순)으로 정렬하여 랭킹을 출력하세요.\n\n[입력]\n학생수N\n이름1 점수1 이름2 점수2 ...\n(예:\n4\n이영희 95 김철수 91 박민수 82 최동호 74)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\nimport java.util.ArrayList;\nimport java.util.Collections;\n\nclass Student implements Comparable<Student> {\n    String name;\n    int score;\n\n    public Student(String name, int score) {\n        this.name = name;\n        this.score = score;\n    }\n\n    @Override\n    public int compareTo(Student o) {\n        return Integer.compare(o.score, this.score);\n    }\n}\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        ArrayList<Student> list = new ArrayList<>();\n        for (int i = 0; i < n; i++) {\n            String name = sc.next();\n            int score = sc.nextInt();\n            list.add(new Student(name, score));\n        }\n\n        Collections.sort(list);\n\n        System.out.println(\"=== 성적 우수순 랭킹 ===\");\n        for (int i = 0; i < list.size(); i++) {\n            System.out.printf(\"[%d등] %s (%d점)\\n\", i + 1, list.get(i).name, list.get(i).score);\n        }\n    }\n}",
        "sample_input": "4\n이영희 95 김철수 91 박민수 82 최동호 74",
        "sample_output": "=== 성적 우수순 랭킹 ===\n[1등] 이영희 (95점)\n[2등] 김철수 (91점)\n[3등] 박민수 (82점)\n[4등] 최동호 (74점)",
        "expected": "=== 성적 우수순 랭킹 ===\n[1등] 이영희 (95점)\n[2등] 김철수 (91점)\n[3등] 박민수 (82점)\n[4등] 최동호 (74점)"
    },
    {
        "id": "day07_중",
        "day": 7,
        "subject": "Java",
        "difficulty": "중",
        "title": "과일 판매 품목 Set 및 판매량 집계 Map (WordFrequencyMap)",
        "desc": "판매 건수 N과 N개의 과일 이름을 입력받아 HashMap을 이용해 각 품목별 판매 수량과 총 판매량을 집계하세요.\n\n[입력]\n판매 건수 N\n과일이름들이 공백으로 주어집니다.\n(예:\n9\n사과 바나나 사과 딸기 바나나 사과 포도 딸기 수박)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\nimport java.util.HashMap;\nimport java.util.Map;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        HashMap<String, Integer> map = new HashMap<>();\n\n        for (int i = 0; i < n; i++) {\n            String fruit = sc.next();\n            map.put(fruit, map.getOrDefault(fruit, 0) + 1);\n        }\n\n        System.out.println(\"=== 과일 가게 판매 현황 분석 ===\");\n        System.out.printf(\"총 판매: %d건 | 고유 품목: %d종\\n\", n, map.size());\n        for (Map.Entry<String, Integer> entry : map.entrySet()) {\n            System.out.printf(\"  - %s: %d건 판매\\n\", entry.getKey(), entry.getValue());\n        }\n    }\n}",
        "sample_input": "9\n사과 바나나 사과 딸기 바나나 사과 포도 딸기 수박",
        "sample_output": "=== 과일 가게 판매 현황 분석 ===\n총 판매: 9건 | 고유 품목: 5종\n  - 포도: 1건 판매\n  - 수박: 1건 판매\n  - 사과: 3건 판매\n  - 바나나: 2건 판매\n  - 딸기: 2건 판매",
        "expected": "=== 과일 가게 판매 현황 분석 ===\n총 판매: 9건 | 고유 품목: 5종\n  - 포도: 1건 판매\n  - 수박: 1건 판매\n  - 사과: 3건 판매\n  - 바나나: 2건 판매\n  - 딸기: 2건 판매"
    },
    {
        "id": "day07_상",
        "day": 7,
        "subject": "Java",
        "difficulty": "상",
        "title": "람다식 & 함수형 인터페이스 기반 상품 필터 파이프라인 (ProductFilterPipeline)",
        "desc": "도서 2권의 정보(제목과 가격)를 입력받아 도서 목록을 출력하세요.\n\n[입력]\n도서명1 가격1 도서명2 가격2\n(예: 자바프로그래밍입문 28000 클린코드 32000)",
        "template": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        // 여기에 코드를 작성하세요\n        \n    }\n}",
        "solution": "import java.util.Scanner;\n\npublic class Solution {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String book1 = sc.next();\n        int price1 = sc.nextInt();\n        String book2 = sc.next();\n        int price2 = sc.nextInt();\n\n        System.out.println(\"[도서 카테고리 목록]\");\n        System.out.printf(\"📚 [도서] %-15s : %,d원\\n\", book1, price1);\n        System.out.printf(\"📚 [도서] %-15s : %,d원\\n\", book2, price2);\n    }\n}",
        "sample_input": "자바프로그래밍입문 28000 클린코드 32000",
        "sample_output": "[도서 카테고리 목록]\n📚 [도서] 자바프로그래밍입문       : 28,000원\n📚 [도서] 클린코드            : 32,000원",
        "expected": "[도서 카테고리 목록]\n📚 [도서] 자바프로그래밍입문       : 28,000원\n📚 [도서] 클린코드            : 32,000원"
    },
    {
        "id": "day08_하",
        "day": 8,
        "subject": "MySQL",
        "difficulty": "하",
        "title": "영업직(SALESMAN) 사원 기본 인적사항 조회",
        "desc": "`EMP` 테이블에서 담당 업무(`JOB`)가 `'SALESMAN'`인 사원들의 사원번호(`EMPNO`), 이름(`ENAME`), 기본급(`SAL`), 커미션(`COMM`)을 조회하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT EMPNO, ENAME, SAL, COMM\nFROM EMP\nWHERE JOB = 'SALESMAN';",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day08_중",
        "day": 8,
        "subject": "MySQL",
        "difficulty": "중",
        "title": "핵심 연구/영업 부서 고액 연봉자 다중 정렬 조회",
        "desc": "부서 번호(`DEPTNO`)가 20번(RESEARCH) 또는 30번(SALES)이고, 급여(`SAL`)가 1,500 이상인 사원의 사원번호, 이름, 부서번호, 급여를 조회하세요. 결과는 급여가 높은 순(내림차순)으로 정렬하고, 급여가 동일할 경우 이름 오름차순(A-Z)으로 정렬하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT EMPNO, ENAME, DEPTNO, SAL\nFROM EMP\nWHERE DEPTNO IN (20, 30) AND SAL >= 1500\nORDER BY SAL DESC, ENAME ASC;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day08_상",
        "day": 8,
        "subject": "MySQL",
        "difficulty": "상",
        "title": "유효 인센티브 수령자의 총 보상 산출 및 랭킹 조회",
        "desc": "데이터베이스에서 `NULL`과의 산술 연산은 `NULL`을 반환하므로 주의해야 합니다. 커미션(`COMM`)이 `NULL`이 아니고 0보다 큰 사원 중, 기본급과 커미션을 합산한 총 보상액(`TOTAL_COMP`)이 2,000 이상인 사원을 탐색하여 총 보상액 기준 내림차순 정렬 조회하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT EMPNO, ENAME, SAL, COMM, (SAL + COMM) AS TOTAL_COMP\nFROM EMP\nWHERE COMM IS NOT NULL AND COMM > 0 AND (SAL + COMM) >= 2000\nORDER BY TOTAL_COMP DESC;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day09_하",
        "day": 9,
        "subject": "MySQL",
        "difficulty": "하",
        "title": "직무별 인원 수 및 평균 급여 집계",
        "desc": "`EMP` 테이블에서 각 담당 업무(`JOB`)별로 사원 수(`EMP_COUNT`)와 평균 급여(`AVG_SAL`)를 집계하세요. 단, 평균 급여는 `ROUND()` 함수를 사용하여 소수점 첫째 자리까지 반올림하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT JOB, COUNT(*) AS EMP_COUNT, ROUND(AVG(SAL), 1) AS AVG_SAL\nFROM EMP\nGROUP BY JOB;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day09_중",
        "day": 9,
        "subject": "MySQL",
        "difficulty": "중",
        "title": "부서별 고액 총급여 부서 추출 및 급여 통계",
        "desc": "부서별(`DEPTNO`)로 총 급여 합계(`SUM(SAL)`)가 5,000 이상인 부서만을 선별하여, 부서번호, 소속 인원 수(`CNT`), 최고 급여(`MAX_SAL`), 최저 급여(`MIN_SAL`), 총 급여(`TOTAL_SAL`)를 조회하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT DEPTNO, COUNT(*) AS CNT, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, SUM(SAL) AS TOTAL_SAL\nFROM EMP\nGROUP BY DEPTNO\nHAVING SUM(SAL) >= 5000;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day09_상",
        "day": 9,
        "subject": "MySQL",
        "difficulty": "상",
        "title": "복합 필터링(WHERE vs HAVING)을 적용한 직무별 급여 분석",
        "desc": "SQL 튜닝 및 최적화에서 개별 행 필터링(`WHERE`)과 그룹 집계 후 필터링(`HAVING`)의 역할을 구분하는 것은 매우 중요합니다.\n1. 직무가 `'PRESIDENT'`가 아니고 개별 급여가 1,000 이상인 사원들만을 대상으로 사전 필터링합니다.\n2. 직무별로 그룹화한 뒤, 평균 급여가 2,000 이상인 직무만 선별하세요.\n3. 직무명, 평균 급여(소수점 1자리 반올림), 총 급여를 평균 급여 내림차순으로 정렬하여 조회하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT JOB, ROUND(AVG(SAL), 1) AS AVG_SAL, SUM(SAL) AS TOTAL_SAL\nFROM EMP\nWHERE JOB != 'PRESIDENT' AND SAL >= 1000\nGROUP BY JOB\nHAVING AVG(SAL) >= 2000\nORDER BY AVG_SAL DESC;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day10_하",
        "day": 10,
        "subject": "MySQL",
        "difficulty": "하",
        "title": "사원 및 소속 부서 정보 내부 조인 (INNER JOIN)",
        "desc": "`EMP` 테이블과 `DEPT` 테이블을 `DEPTNO` 외래키/기본키 관계로 결합하여, 사원번호(`EMPNO`), 이름(`ENAME`), 소속 부서명(`DNAME`), 부서 위치(`LOC`)를 조회하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT e.EMPNO, e.ENAME, d.DNAME, d.LOC\nFROM EMP e\nINNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day10_중",
        "day": 10,
        "subject": "MySQL",
        "difficulty": "중",
        "title": "미배치 부서까지 포함한 부서별 사원 수 집계 (LEFT OUTER JOIN)",
        "desc": "현재 사원이 한 명도 소속되어 있지 않은 40번(`OPERATIONS`) 부서까지 누락 없이 모두 결과에 포함되도록 외부 조인을 사용하고, 각 부서별 실제 사원 수(`COUNT(e.EMPNO)`)를 집계하세요. (`COUNT(*)`를 사용하면 사원이 없는 부서도 1로 카운트되므로 주의)",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT d.DEPTNO, d.DNAME, COUNT(e.EMPNO) AS EMP_COUNT\nFROM DEPT d\nLEFT JOIN EMP e ON d.DEPTNO = e.DEPTNO\nGROUP BY d.DEPTNO, d.DNAME\nORDER BY d.DEPTNO;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day10_상",
        "day": 10,
        "subject": "MySQL",
        "difficulty": "상",
        "title": "사원-관리자 계층(SELF JOIN) 및 급여 등급 비등가 조인(NON-EQUI JOIN)",
        "desc": "하나의 쿼리 안에서 계층 구조와 범위 매핑을 동시에 수행합니다.\n1. `EMP` 테이블을 자기 자신과 조인(`SELF JOIN`)하여 사원의 직속 상사 이름(`MANAGER`)을 매핑하되, 상사가 없는 사원(KING)은 `'최상위관리자'`로 표시하세요 (`IFNULL` 활용).\n2. `SALGRADE` 테이블과 비등가 조인(`BETWEEN s.LOSAL AND s.HISAL`)하여 해당 사원의 급여 등급(`GRADE`)을 매핑하세요.\n3. 급여 등급 높은 순, 급여가 높은 순으로 정렬 조회하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT e.ENAME AS EMPLOYEE, \n       IFNULL(m.ENAME, '최상위관리자') AS MANAGER, \n       e.SAL, \n       s.GRADE\nFROM EMP e\nLEFT JOIN EMP m ON e.MGR = m.EMPNO\nINNER JOIN SALGRADE s ON e.SAL BETWEEN s.LOSAL AND s.HISAL\nORDER BY s.GRADE DESC, e.SAL DESC;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day11_하",
        "day": 11,
        "subject": "MySQL",
        "difficulty": "하",
        "title": "전체 평균 급여를 초과하는 고연봉 사원 조회 (단일행 서브쿼리)",
        "desc": "회사 전체 사원의 평균 급여(`AVG(SAL)`)보다 높은 급여를 받는 사원의 사원번호, 이름, 급여를 조회하세요. 결과는 급여가 높은 순으로 정렬합니다.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT EMPNO, ENAME, SAL\nFROM EMP\nWHERE SAL > (SELECT AVG(SAL) FROM EMP)\nORDER BY SAL DESC;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day11_중",
        "day": 11,
        "subject": "MySQL",
        "difficulty": "중",
        "title": "각 부서별 최고 급여 수령자 조회 (다중컬럼 서브쿼리)",
        "desc": "각 부서(`DEPTNO`)별로 가장 많은 급여(`MAX(SAL)`)를 받는 사원들의 사원번호, 이름, 부서번호, 급여를 조회하세요. 다중 컬럼 서브쿼리(`(DEPTNO, SAL) IN (...)`)를 활용하여 부서번호 오름차순으로 정렬하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "SELECT EMPNO, ENAME, DEPTNO, SAL\nFROM EMP\nWHERE (DEPTNO, SAL) IN (\n    SELECT DEPTNO, MAX(SAL)\n    FROM EMP\n    GROUP BY DEPTNO\n)\nORDER BY DEPTNO;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day11_상",
        "day": 11,
        "subject": "MySQL",
        "difficulty": "상",
        "title": "인프라 데이터 정리 및 아카이빙 트랜잭션 (DML + TRANSACTION)",
        "desc": "운영 DB의 테이블 비대화를 방지하기 위해 오래된 로그나 특정 대상(`JOB = 'CLERK'`) 데이터를 별도 아카이브 백업 테이블(`EMP_BACKUP`)로 이관하고 원본에서 삭제하는 작업을 원자적(Atomic) 트랜잭션으로 구성하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "START TRANSACTION;\n\nCREATE TABLE IF NOT EXISTS EMP_BACKUP AS \nSELECT * FROM EMP WHERE 1 = 0;\n\nINSERT INTO EMP_BACKUP \nSELECT * FROM EMP WHERE JOB = 'CLERK';\n\nDELETE FROM EMP WHERE JOB = 'CLERK';\n\nCOMMIT;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day12_하",
        "day": 12,
        "subject": "MySQL",
        "difficulty": "하",
        "title": "도서 인벤토리 테이블 생성 (기본 DDL)",
        "desc": "도서관에서 관리할 도서 정보를 저장하는 `TB_BOOK` 테이블을 생성하세요.\n* `ISBN`: 최대 20자 가변문자열, 기본키(`PRIMARY KEY`)\n* `TITLE`: 최대 100자 가변문자열, 필수값(`NOT NULL`)\n* `AUTHOR`: 최대 50자 가변문자열, 필수값(`NOT NULL`)\n* `PRICE`: 정수형, 기본값 0, 필수값(`NOT NULL`)\n* `PUBLISHED_DATE`: 날짜형(`DATE`)",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "CREATE TABLE TB_BOOK (\n    ISBN VARCHAR(20) PRIMARY KEY,\n    TITLE VARCHAR(100) NOT NULL,\n    AUTHOR VARCHAR(50) NOT NULL,\n    PRICE INT DEFAULT 0 NOT NULL,\n    PUBLISHED_DATE DATE\n);",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day12_중",
        "day": 12,
        "subject": "MySQL",
        "difficulty": "중",
        "title": "테이블 스키마 수정 및 카테고리 컬럼 추가 (ALTER TABLE)",
        "desc": "`TB_BOOK` 테이블에 도서 분류를 관리하기 위해 `CATEGORY` 컬럼(최대 30자 가변문자열, 기본값 `'일반'`, 필수값 `NOT NULL`)을 추가하세요.",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "ALTER TABLE TB_BOOK \nADD COLUMN CATEGORY VARCHAR(30) DEFAULT '일반' NOT NULL;",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day12_상",
        "day": 12,
        "subject": "MySQL",
        "difficulty": "상",
        "title": "회원 및 대출 이력 무결성 제약조건 테이블 설계 (FK CASCADE & CHECK)",
        "desc": "회원(`TB_MEMBER`) 정보와 도서 대출 이력을 관리하는 `TB_RENTAL` 테이블을 설계합니다.\n1. `RENTAL_ID`: 자동 증가(`AUTO_INCREMENT`), 기본키\n2. `MEMBER_ID`: `TB_MEMBER`의 `MEMBER_ID`를 참조하는 외래키. 회원 탈퇴 시 관련 대출 이력도 자동 연쇄 삭제(`ON DELETE CASCADE`)되어야 합니다.\n3. `ISBN`: `TB_BOOK`의 `ISBN`을 참조하는 외래키 (`ON DELETE CASCADE`)\n4. `STATUS`: 대출 상태로, `'RENTED'`(대출중), `'RETURNED'`(반납완료), `'OVERDUE'`(연체) 중 하나의 값만 허용하도록 `CHECK` 제약조건을 부여하세요.\n5. `RENTAL_DATE`: 타임스탬프 기본값 현재 시각",
        "template": "-- 여기에 SQL 쿼리를 작성하세요\nSELECT * FROM EMP;",
        "solution": "CREATE TABLE TB_MEMBER (\n    MEMBER_ID INT PRIMARY KEY,\n    NAME VARCHAR(30) NOT NULL,\n    PHONE VARCHAR(15) UNIQUE NOT NULL\n);\n\nCREATE TABLE TB_RENTAL (\n    RENTAL_ID INT AUTO_INCREMENT PRIMARY KEY,\n    MEMBER_ID INT,\n    ISBN VARCHAR(20),\n    STATUS VARCHAR(10) NOT NULL,\n    RENTAL_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    CONSTRAINT CK_RENTAL_STATUS CHECK (STATUS IN ('RENTED', 'RETURNED', 'OVERDUE')),\n    CONSTRAINT FK_RENTAL_MEMBER FOREIGN KEY (MEMBER_ID) \n        REFERENCES TB_MEMBER(MEMBER_ID) ON DELETE CASCADE,\n    CONSTRAINT FK_RENTAL_BOOK FOREIGN KEY (ISBN) \n        REFERENCES TB_BOOK(ISBN) ON DELETE CASCADE\n);",
        "sample_input": "MySQL DB 스키마 및 레코드",
        "sample_output": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)",
        "expected": "결과 레코드 집합 (SQL SELECT 조회 결과 테이블 반환)"
    },
    {
        "id": "day13_하",
        "day": 13,
        "subject": "Web",
        "difficulty": "하",
        "title": "온라인 쇼핑몰 회원가입 폼 (SignUpForm)",
        "desc": "아이디, 비밀번호, 이메일, 성별(라디오 버튼), 필수 약관 동의(체크박스), 가입 버튼을 포함하는 표준 HTML5 회원가입 폼을 작성하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day13_중",
        "day": 13,
        "subject": "Web",
        "difficulty": "중",
        "title": "시맨틱 태그 기반 카페 메뉴판 (CafeMenuTable)",
        "desc": "웹 표준 시맨틱 태그(`<header>`, `<main>`, `<article>`, `<footer>`)와 구조화된 데이터 표 태그(`<table>`, `<caption>`, `<thead>`, `<tbody>`, `<th scope=\"col\">`)를 활용하여 카페 음료 메뉴판을 마크업하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day13_상",
        "day": 13,
        "subject": "Web",
        "difficulty": "상",
        "title": "웹 접근성(ARIA) 및 정규식 검증 상품 등록 폼 (ProductRegisterForm)",
        "desc": "쇼핑몰 관리자가 상품을 등록할 때,\n* 상품 식별코드에 정규식 패턴(`pattern=\"^[A-Z]{3}-[0-9]{4}$\"`)과 도움말을 `aria-describedby`로 연결\n* 이미지 파일 업로드(`accept=\"image/*\"`)와 멀티파트 인코딩(`enctype=\"multipart/form-data\"`)을 적용하세요.",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day14_하",
        "day": 14,
        "subject": "Web",
        "difficulty": "하",
        "title": "상품 라벨 및 상태 뱃지 디자인 (ProductBadge)",
        "desc": "쇼핑몰 상품에 부착되는 `BEST`, `30% SALE`, `일시품절` 뱃지를 `inline-block`, 테두리 둥글기(`border-radius: 6px`), 적절한 안쪽 여백(`padding`) 및 테마 색상으로 스타일링하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day14_중",
        "day": 14,
        "subject": "Web",
        "difficulty": "중",
        "title": "Flexbox 기반 상품 카드 리스트 (ProductCardFlexbox)",
        "desc": "상품 카드를 Flexbox 구조(`display: flex; flex-direction: column; justify-content: space-between;`)로 배치하고, 하단 가격과 장바구니 버튼을 양끝 정렬(`justify-content: space-between;`) 및 마우스 Hover 시 살짝 떠오르는 애니메이션(`transform: translateY(-4px);`)을 적용하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day14_상",
        "day": 14,
        "subject": "Web",
        "difficulty": "상",
        "title": "반응형 CSS Grid 기획전 상품 갤러리 (ResponsiveProductGrid)",
        "desc": "화면 크기에 따라 1열부터 4열까지 자동으로 열 개수가 유연하게 조절되는 기획전 상품 목록을 `display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 20px;`로 구축하고, 모바일 미디어 쿼리(`@media (max-width: 768px)`)를 작성하세요.",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day15_하",
        "day": 15,
        "subject": "Web",
        "difficulty": "하",
        "title": "재고 있는 상품 필터링 및 이름 추출 (filter & map)",
        "desc": "장바구니 상품 객체 배열에서 품절되지 않고 구매 가능한(`inStock === true`) 상품만 선별(`filter`)하고, 해당 상품들의 이름(`name`)만을 담은 배열을 반환(`map`)하는 함수를 작성하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day15_중",
        "day": 15,
        "subject": "Web",
        "difficulty": "중",
        "title": "특정 상품의 구매 수량 변경 함수 (불변성 유지 업데이트)",
        "desc": "장바구니에서 특정 `id` 상품의 구매 수량(`quantity`)을 갱신하는 함수를 작성하세요. 원본 배열을 직접 수정하지 않고 스프레드 연산자(`...`)와 `map()`을 활용하여 불변성을 유지해야 하며, 최소 수량은 1개 이상으로 보정하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day15_상",
        "day": 15,
        "subject": "Web",
        "difficulty": "상",
        "title": "장바구니 총 주문 금액 및 무료 배송/할인 계산기 (reduce)",
        "desc": "재고가 있는 상품들의 총 상품 금액(소계 합산)을 `reduce()`로 구하고, 쿠폰 할인(기본 10%) 적용 후 실 결제 금액이 50,000원 이상이면 배송비 무료(미만 3,000원) 정책을 적용한 최종 결제 요약 객체를 반환하는 함수를 작성하세요.",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day16_하",
        "day": 16,
        "subject": "Web",
        "difficulty": "하",
        "title": "비동기 상품 상세 조회 함수 (Promise & async/await)",
        "desc": "상품 ID를 받아 지연 시간 후 상품 상세 객체(`{ id, title, price, stock }`)를 비동기로 반환하고, 존재하지 않는 상품 ID(`\"P-ERROR\"`)일 경우 에러를 던지는 비동기 함수를 작성하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day16_중",
        "day": 16,
        "subject": "Web",
        "difficulty": "중",
        "title": "외부 위젯 데이터(환율, 날씨, 공지) 병렬 수합 (Promise.all & Promise.race)",
        "desc": "쇼핑몰 메인 대시보드 구성을 위해 환율, 날씨, 배송공지 3개의 비동기 프로미스를 생성하고:\n1. `Promise.race()`로 가장 먼저 도착한 정보를 화면에 먼저 표시\n2. `Promise.all()`로 3개 위젯 데이터를 일괄 수합하여 종합 대시보드 데이터를 구성하세요.\n\n---",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    },
    {
        "id": "day16_상",
        "day": 16,
        "subject": "Web",
        "difficulty": "상",
        "title": "쇼핑몰 결제 승인 API 지수 백오프 자동 재시도 래퍼",
        "desc": "결제 대행사(PG) 서버와의 일시적인 통신 순단에 대비하여, 최대 3회까지 지수 지연($100ms, 200ms, 400ms...$)을 두고 자동으로 재호출을 시도하는 고차 비동기 재시도 함수 `requestPaymentWithRetry()`를 구현하세요.",
        "template": "// 여기에 자바스크립트 코드를 작성하세요\n",
        "solution": "",
        "sample_input": "없음",
        "sample_output": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인",
        "expected": "HTML/CSS 렌더링 및 콘솔 실행 결과 확인"
    }
];
